#!/usr/bin/env bash

set -ex

# This is the master script for the capsule. When you click "Reproducible Run", the code in this file will execute.
python -u "mnist/fgsm_pytorch_mnist.py" > /results/fgsm_mnist.txt
